agents:
- agent_name: "preprocessing"
  prompt: "preprocessing-agent.yaml"
- agent_name: "query"
  prompt: "query.yaml"
- agent_name: "search"
  prompt: "search-agent.yaml"
- agent_name: "persona"
  prompt: "persona.yaml"
- agent_name: "coaching"
  prompt: "coach.yaml"
- agent_name: "feedback"
  prompt: "feedback-agent.yaml"
