agents:
- agent_name: "preprocessing"
  prompt: "preprocessing-agent.yaml"
- agent_name: "query"
  prompt: "query-agent.yaml"
- agent_name: "search"
  prompt: "search-agent.yaml"
- agent_name: "persona"
  prompt: "persona-agent.yaml"
- agent_name: "context_manager"
  prompt: "context-manager-agent.yaml"
- agent_name: "coaching"
  prompt: "coaching-agent.yaml"
- agent_name: "feedback"
  prompt: "feedback-agent.yaml"
